version: '3.8'

services:
  app:
    build: .
    container_name: ricardo_bot_app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./credentials.json:/app/scripts/credentials.json:ro
      - ./token.json:/app/scripts/token.json:ro
    expose:
      - "8000"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ricardo_bot_tunnel
    restart: unless-stopped
    env_file:
      - .env
    # ðŸ”´ Este token de TÃºnel lo recibes de Cloudflare
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    depends_on:
      - app
